=== rakesh-patnaik/XMLSchemaDesign/discussions.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT discussion (topic,viewCount,subject,question,postingUser,replies)>
<!ATTLIST discussion device (iPhone|Mac|AppleWatch|iPad|iPod|AppleTV|HomePod) #REQUIRED>
<!ATTLIST discussion
  discussionId NMTOKEN #REQUIRED
  postingDate CDATA #REQUIRED>

<!ELEMENT topic (#PCDATA)>

<!ELEMENT viewCount (#PCDATA)>

<!ELEMENT subject (#PCDATA)>

<!ELEMENT question (#PCDATA)>

<!ELEMENT postingUser (userLevel,profileName)>
<!ATTLIST postingUser
  userId NMTOKEN #REQUIRED>

<!ELEMENT userLevel (levelName,uesrPoints)>

<!ELEMENT levelName (#PCDATA)>

<!ELEMENT uesrPoints (#PCDATA)>

<!ELEMENT profileName (#PCDATA)>

<!ELEMENT replies (reply)*>

<!ELEMENT reply (replies*|replyBody|replyingUser)*>
<!ATTLIST reply
  helpful (yes|no) #IMPLIED
  replyDate CDATA #REQUIRED
  solved (yes|no) #IMPLIED>

<!ELEMENT replyBody (#PCDATA)>

<!ELEMENT replyingUser (userLevel,profileName)>
<!ATTLIST replyingUser
  userId NMTOKEN #REQUIRED>

=== rakesh-patnaik/XMLSchemaDesign/document2.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE discussion PUBLIC "discussions.apple.com/cs598"
  "https://raw.githubusercontent.com/rakesh-patnaik/XMLSchemaDesign/master/discussions.dtd">
<discussion postingDate="Sep 28, 2019 11:00 AM" discussionId="112233" device="iPhone">
    <topic>Using iPhone</topic>
    <viewCount>201</viewCount>
    <subject>iPhone X iOS 13 Dark Mode Bug</subject>
    <question>
        Hi,
            I have an issue with my iPhone X after iOS 13 update. 
            I started to use dark mode because I like it, but when brightness is not set on 100% 
            I see some annoying flickering during scrolling where Dark Grey and Black content are overlapped e.g. settings app
    </question>
    
    <postingUser userId="6661">
        <userLevel>
            <levelName>Level  1</levelName>
            <uesrPoints>8</uesrPoints>
        </userLevel>
        <profileName>nickciava98</profileName>
    </postingUser>
    <replies>
        <reply replyDate="Sep 28, 2019 5:54 PM">
            <replyingUser userId="5551">
                <userLevel>
                    <levelName>Level 1</levelName>
                    <uesrPoints>4</uesrPoints>
                </userLevel>
                <profileName>iPhoneUser404</profileName>
            </replyingUser>
            <replyBody>
                Iâ€™ve had this same issue on my iPhone XS where the blacks have a sort of motion blur effect 
                where when you scroll it overlaps on other colors, this does not affect older models without 
                an oled such as the 7+ which I tested on and it did not  have this bug on that LCD.
            </replyBody>
            <replies>
                <reply replyDate="Sep 29, 2019 12:32 AM">
                    <replyingUser userId="6661">
                        <userLevel>
                            <levelName>Level 1</levelName>
                            <uesrPoints>8</uesrPoints>
                        </userLevel>
                        <profileName>nickciava98</profileName>
                    </replyingUser>
                    <replyBody>
                        Exactly, I think it is a software bug
                    </replyBody>
                </reply>              
            </replies>
        </reply>
    </replies>
</discussion>

=== rakesh-patnaik/XMLSchemaDesign/document1.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE discussion PUBLIC "discussions.apple.com/cs598"
  "https://raw.githubusercontent.com/rakesh-patnaik/XMLSchemaDesign/master/discussions.dtd">
<discussion postingDate="Sep 29, 2019 11:07 AM"
	discussionId="12345" device="iPhone">
	<topic>iPhone Hardware</topic>
	<viewCount>229</viewCount>
	<subject>Engraving</subject>
	<question>
		Can I have my iPhone 7 engraved after Iâ€™ve purchased it?
	</question>

	<postingUser userId="5551">
		<userLevel>
			<levelName>Level 1</levelName>
			<userPoints>8</userPoints>
		</userLevel>
		<profileName>CXI</profileName>
	</postingUser>
	<replies>
		<reply replyDate="Sep 29, 2019 11:11 AM" helpful="yes">
			<replyingUser userId="6661">
				<userLevel>
					<levelName>Level 6</levelName>
					<userPoints>19709</userPoints>
				</userLevel>
				<profileName>Johnathan Burger</profileName>
			</replyingUser>
			<replyBody>
				Once you have. Bought it, it's yours to what you want with
				it. Apple won't do it but you can find some who will.
			</replyBody>
		</reply>
		<reply replyDate="Sep 29, 2019 12:31 PM">
			<replyingUser userId="5551">
				<userLevel>
					<levelName>Level 1</levelName>
					<userPoints>8</userPoints>
				</userLevel>
				<profileName>CXI</profileName>
			</replyingUser>
			<replyBody>
				Thanks, but is it safe for the iPhone to do so?
			</replyBody>
			<replies>
				<reply replyDate="Sep 29, 2019 12:50 PM" helpful="yes"
					solved="yes">
					<replyingUser userId="7771">
						<userLevel>
							<levelName>Level 6</levelName>
							<userPoints>10213</userPoints>
						</userLevel>
						<profileName>y_p_w</profileName>
					</replyingUser>
					<replyBody>
						Exactly, I think it is a software bug
					</replyBody>
				</reply>
			</replies>
		</reply>
	</replies>
</discussion>

=== rakesh-patnaik/XMLSchemaDesign/document4.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE discussion PUBLIC "discussions.apple.com/cs598"
  "https://raw.githubusercontent.com/rakesh-patnaik/XMLSchemaDesign/master/discussions.dtd">
<discussion postingDate="Sep 20, 2019 4:45 AM" discussionId="443322" device="iPhone" topic="Using iPhone">
    <viewCount>33</viewCount>
    <subject>Unable to rearrange app icons in ios 13</subject>
    <question>
        After upgrading to iOS 13 and trying to rearrange app icons this is what happens: I long press the app icon and select "Rearrange Apps" from the context menu. Apps show the "x" mark and start wiggle. I try to move/rearrange an icon and after a 1-2 second delay the icon moves but then freezes on the screen without the "x" mark although all other icons wiggle. The specific app icon is no longer movable and the sliding of the screen left to right becomes sluggish. After a while, and without me being able to do anything useful the "x" marks disappear, the wiggling stops and the app icon that I intended to move stays where it was initially. Looks like a MAJOR bug in iOS.
    </question>
    <postingUser userId="2211">
        <userLevel>
            <levelName>Level 1</levelName>
            <uesrPoints>13</uesrPoints>
        </userLevel>
        <profileName>DaliGR</profileName>
    </postingUser>
    <replies>
        <reply replyDate="Sep 21, 2019 3:56 AM" solved="yes" helpful="yes">
            <replyingUser userId="33221">
                <userLevel>
                    <levelName>Level 1</levelName>
                    <uesrPoints>14</uesrPoints>
                </userLevel>
                <profileName>PaulTJ</profileName>
            </replyingUser>
            <replyBody>
                SOLVED - I was having the exact same problem. I had the Zoom function enabled with the three finger double tap active in accessibility settings which was the cause of this problem. Once I disabled this in settings moving the icons around was back to normal for me - what a relief! Hope this helps others who have same issues - check your zoom settings!!
            </replyBody>
        </reply>
    </replies>
</discussion>

=== rakesh-patnaik/XMLSchemaDesign/document3.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE discussion PUBLIC "discussions.apple.com/cs598"
  "https://raw.githubusercontent.com/rakesh-patnaik/XMLSchemaDesign/master/discussions.dtd">
<discussion postingDate="Sep 26, 2019 1:42 PM" discussionId="222333" device="Apple Watch" topic="Using Apple Watch">
    <viewCount>23</viewCount>
    <subject>Anyone having issues with their watch locking while on their wrist.</subject>
    <question>
        Is anyone else having an issue with their watch constantly locking for no reason. 
        I haven't changed the tightness and never had a problem prior to the new update. 
        Its very annoying.
    </question>
    <postingUser userId="7771">
        <userLevel>
            <levelName>Level 1</levelName>
            <uesrPoints>4</uesrPoints>
        </userLevel>
        <profileName>Faunsnyder</profileName>
    </postingUser>
    <replies>
        <reply replyDate="Sep 28, 2019 8:29 PM">
            <replyingUser userId="6661">
                <userLevel>
                    <levelName>Community Specialist</levelName>
                    <uesrPoints>100023</uesrPoints>
                </userLevel>
                <profileName>revbill222</profileName>
            </replyingUser>
            <replyBody>
                Hello Faunsnyder and welcome to Apple Support Communities. 
                It seems like you are having some issues with the Apple Watch locking while you are wearing it. 
                I'll be happy to help look into this with you. When you say "locking" do you mean that you have to enter the passcode? 
                If you open the Watch app on the paired iPhone and scroll to Passcode and tap that, is Wrist Detection enabled?
            </replyBody>
        </reply>
    </replies>
</discussion>
